name: Mirroring

on:
  delete:
  pull_request:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pathscale/WorkTable' }}
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:pathscale/WorkTable.git"
          source_branch: "main"
          destination_repo: "git@github.com:insolvent-capital/WorkTable.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets._SSH_PRIVATE_KEY }}